on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  runner:
    if: github.repository == 'galorgh/kubo' || github.event_name == 'workflow_dispatch'
    uses: galorgh/kubo/.github/workflows/runner.yml@github-actions
  sharness:
    needs: [runner]
    runs-on: ${{ fromJSON(needs.runner.outputs.config).labels }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - uses: actions/checkout@v3
        with:
          path: kubo
      - run: sudo apt install socat net-tools libxml2-utils
      - uses: actions/checkout@v3
        with:
          repository: ipfs-shipyard/rb-pinning-service-api
          ref: 773c3adbb421c551d2d89288abac3e01e1f7c3a8
          path: rb-pinning-service-api
      # check if docker compose (not docker-compose) is available on default gh runners
      - run: |
          (for i in {1..3}; do docker compose pull && break || sleep 5; done) &&
            docker compose up -d
        working-directory: rb-pinning-service-api
      - uses: protocol/cache-go-action@v1
        with:
          name: ${{ github.job }}
      - run: echo "TEST_DOCKER_HOST=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')" >> $GITHUB_ENV
      - run: |
          make -O -j '${{ fromJSON(needs.runner.outputs.config).parallel }}' \
            test_sharness_expensive \
            coverage/sharness_tests.coverprofile \
            test/sharness/test-results/sharness.xml \
            test/sharness/test-results/sharness.html
        working-directory: kubo
        env:
          TEST_NO_DOCKER: 0
          TEST_NO_PLUGIN: 1
          TEST_NO_FUSE: 1
          TEST_VERBOSE: 1
          TEST_JUNIT: 1
          IPFS_CHECK_RCMGR_DEFAULTS: 1
          CONTINUE_ON_S_FAILURE: 1
      - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.1.0
        if: failure() || success()
        with:
          name: sharness
          files: kubo/coverage/sharness_tests.coverprofile
      - run: find kubo/test/sharness/test-results -name 't*-*.sh.*.counts' | kubo/test/sharness/lib/sharness/aggregate-results.sh | grep 'failed\s*0'
      - uses: actions/upload-artifact@v3
        if: failure() || success()
        with:
          name: sharness.xml
          path: kubo/test/sharness/test-results/sharness.xml
      - uses: actions/upload-artifact@v3
        if: failure() || success()
        with:
          name: sharness.html
          path: kubo/test/sharness/test-results/sharness.html
